### ISSUE TITLE
Missing Textures on Jedi Outcast maps

### ISSUE THREAD

**Issue by QSR-90** [eternalcodes/EternalJK#109]
EternalJK over Jedi Academy v1.0.1.0, Windows 10. Works like a charm except when I'm trying to load old [maps from Jedi Outcast](https://www.moddb.com/games/star-wars-jedi-academy/addons/jedi-outcast-maps-for-jedi-academy) adapted for Jedi Academy. Some textures load fine and some are obviously missing. Console returns the following errors: 
![Annotation 2020-07-28 155131](https://user-images.githubusercontent.com/68952892/88798572-c3a2df80-d1ad-11ea-8863-e88d81865565.png)
![Annotation 2020-07-29 150920](https://user-images.githubusercontent.com/68952892/88798573-c4d40c80-d1ad-11ea-94e9-b136081b3194.png)

Used to work fine before I discovered EternalJK, but without it game just doesn't look so good on widescreen so I would really like to keep using this mod. Ideally, with the good old Jedi Outcast maps as well. 

Is there any chance it will be fixed?

**Comment by Bucky21659** [comment]
Hi, what JK2 map pack are you using?  I usually recommend the JK2 MP map pack from here
 http://www.playja.pro/?page=maps

**Comment by QSR-90** [comment]
> what JK2 map pack are you using
There is a link to exact map pack in my first message - perhaps I didn't make it visible enough, but it doesn't really matter now. 

The map pack you've recommended actually works. Textures are back in place and bot route seems fine. I'm really happy, thank you for replying.
