### ISSUE TITLE
Can't find my CFG files

### ISSUE THREAD

**Issue by dinurdo** [eternalcodes/EternalJK#24]
Hi since using this with Steam I can't find my CFG files. Where are they? very frustrating. I am not configged now.

**Comment by Atlas1011** [comment]
Your basejka CFG, (the one that runs on start-up) is /GameData/eternaljk/**eternaljk.cfg**, and for any other mod, the cfg used is /GameData/"Mod Name"/**eternaljk.cfg**. Now when you /writeconfig a new CFG while in-game, the new .cfg is placed in one of the above folders depending on if you were playing basejka or a mod.

**Comment by dinurdo** [comment]
Sorry, I think this was in reference to an older build. After searching for the cfg files I had found them in MyDocuments, which is very strange to me. I'm used to the jamp.exe behavior that comes with Steam. I think this is no longer an issue. Close this please.
