### ISSUE TITLE
icons are NOT consistent

### ISSUE THREAD

**Issue by ghost** [eternalcodes/EternalJK#33]
in my taskbar -- it shows the OpenJK icon and **NOT** the new ETJK icon. I believe Bucky is aware of this issue, but I'm bringing it to your attention, Eternal.

**Comment by steveei** [comment]
I have attempted to solve this issue as well, and etjk will not display the updated .ico file. It compiles along with it but fails to display on taskbar/start menu. Can you please look at this in more depth? @eternalcodes -Steve

**Comment by Bucky21659** [comment]
fixed
