### ISSUE TITLE
Console scroll up crash on join

### ISSUE THREAD

**Issue by ghost** [eternalcodes/EternalJK#49]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Win10 x64 Pro

**Is this for single player or multiplayer?**
Multiplayer on playjapro ups gaming defrag servy.

**Description of the bug (and if possible, steps to reproduce the bug):**
Using latest clientside. I join playjapro defrag gamering server and open console right away and scroll up. (Wheel or PGUP, both work) Then, my client (EternalJK - by eternalcodes) crashes.

**What did you expect to happen instead?**
I expected to be able to read my console like on jamp.exe

I thought this an already **fixed** issue.

**Comment by videoP** [comment]
type
/clear
/gfxinfo
and scroll up, does it crash then as well?

**Comment by dinurdo** [comment]
Yes, it crashes then as well. -dinurdo

**Comment by videoP** [comment]
Newest DinurdoJK fixes this then, since the GL_ console spam and the pk3 list console spam are not shown on map load unless you have r_verbose or fs_debug, respectively.

Now that the problem is located to gfxinfo, @eternalcodes should be able to find out what he changed to cause this.
