### ISSUE TITLE
con_notifyname is -- ~~BUGGED~~

### ISSUE THREAD

**Issue by videoP** [eternalcodes/EternalJK#52]
con_notifyname "player", minimize, player is not notified when someone says his name

should move this, along with the engine logging to here though, on "chat" or "teamchat" command
https://github.com/eternalcodes/EternalJK/blob/master/codemp/client/cl_cgame.cpp#L482

**Comment by dinurdo** [comment]
Hey guys this is no longer an issue. Its fixed on DinurdoJK™. Check it out here https://github.com/dinurdo/DinurdoJK
