### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by tallyie** [eternalcodes/EternalJK#56]
when launching multiple clients, the screen turns white and it takes 5 seconds in order to load the main menu. i want it to launch IMMEDIATELY without any visual glitches.

**Comment by videoP** [comment]
I think this is related to the new widescreen loading JPGs bucky added.  

If thats the problem maybe a fix would be that if they cant be loaded they would fallback to the default instead of whitescreening.

**Comment by eternalcodes** [comment]
fixed in bec5332
