### ISSUE TITLE
model default/f

### ISSUE THREAD

**Issue by tallyie** [eternalcodes/EternalJK#58]
i do not know what this is, where is my kyle katarn for default skins? it is a weird figure with a goatee and dark glasses. cringe. please revert this change to kyle katarn for nostalgic purposes.

**Comment by videoP** [comment]
Actually agree with this one, no reason to change default behaviour, and the model quality is poor

**Comment by eternalcodes** [comment]
This was a change made by @Bucky21659. We wanted a new default model to replace kyle.
