### ISSUE TITLE
View all profile skins

### ISSUE THREAD

**Issue by eternalcodes** [eternalcodes/EternalJK#69]
C4N: In JA++, any model that has a skin even if its name is **_anything (not only _default _red and _blue) is shown there even if the icon is missing.

We'll want to do something similar like create a filter for all, or a filter to show the rest of the skins that aren't currently displayed. We may want to ignore skins without icons, or try to add icons that are missing.

The RGB filter also needs to improved so that the filter doesn't display if the skins don't exist.

![unknown](https://user-images.githubusercontent.com/4057312/36074698-65ef4770-0f09-11e8-8e7d-2e04a4ada690.png)

**Comment by Arlu3n** [comment]
Is there any update on this?

**Comment by Bucky21659** [comment]
Present in current release with ui_showAllSkins 1
