### ISSUE TITLE
Rich Presence on Mac

### ISSUE THREAD

**Issue by RedRaspberry** [eternalcodes/EternalJK#79]
Reporting a bug? Please make sure you've given the following information in detail - thanks!

**Operating system and version:**
Mac- Sierra 10.12.6

**Description of the bug (and if possible, steps to reproduce the bug):**
Not really a bug, more of a feature for windows that doesn't work on mac
Reproduce is easy, just use etjk on any mac.

**What did you expect to happen instead?**
To be able to use the rich presence features within discord to jump into games, and so that others can see what I'm doing in game.

**Comment by Bucky21659** [comment]
Discord rich presence wasn't publically released on any platform until the 1.5.4 release.
It is now available on all platforms.
