### ISSUE TITLE
cgame currently crashes

### ISSUE THREAD

**Issue by AlexCSilva** [eternalcodes/EternalJK#8]
Reporting a bug? Please make sure you've given the following information - thanks!

**Operating system and version:**
Windows and Linux

**Is this for single player or multiplayer?**
Multiplayer

**Description of the bug (and if possible, steps to reproduce the bug):**
cgame currently crashes
not yet sure what causes it. will try to fix it

**What did you expect to happen instead?**
cgame to work lol

**Comment by eternalcodes** [comment]
Fixed in 7f89e408e24db297110b4ab3f952a52f33a55ddf
