### ISSUE TITLE
Numeric binds not working

### ISSUE THREAD

**Issue by genetix111** [eternalcodes/EternalJK#92]
Reporting a bug? Please make sure you've given the following information in detail - thanks!

**Operating system and version:** Windows 10 Pro 64bit

**Description of the bug (and if possible, steps to reproduce the bug):** On version 1.5.0, numeric binds are not working from the numpad.

**What did you expect to happen instead?** I wanted to call a bind that is on a number, but it doesn't work from the numeric key. I can write numbers to chat, but can't call binds from it.

**Comment by Bucky21659** [comment]
Last release changed it so the numberpad would use KP_ binds instead of 1/2/3/4/5 with numlock on, turning numlock off should have the old behavior (besides 5 not working for some reason).

You can also bind KP_LEFTARROW, KP_5, KP_RIGHTARROW, etc. to whatever you also have on 4/5/6.
