### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by empresstaethelil** [eternalcodes/EternalJK#93]
Reporting a bug? Please make sure you've given the following information in detail - thanks!

**Operating system and version:**
Windows 10 - Home

**Description of the bug (and if possible, steps to reproduce the bug):**
No servers show up in serverlist, when connecting through console, get stuck on 'Awaiting Connection'. Issue doesn't present itself when using JA+ ect.

Installed by extracting the .zip into the gamedata file, tried renaming the .exe to jamp, launching as admin, launching through steam, ...

**What did you expect to happen instead?**
Be able to join a server.

Any ideas? Thanks already!

**Comment by eternalcodes** [comment]
Can't reproduce, your firewall might be blocking the eternaljk executable.
